### PR TITLE
Members in Chat Inspector

### PR DESCRIPTION
**Pull request by levochkaa**
Added list of members of a chat to chat inspector 

Some bugs when scrolling fast, `.anchorPreference(key:value:transform:)` might fix

### CODE REVIEW

**Comment by ggoraa** [comment]
I have encountered some issues while testing this PR, which is when changing chats, the user list does not update, please fix it

**Comment by ggoraa** [comment]
And also the user list update process introduces tremendous lag, probably related to fetching everything on the main thread

**Comment by levochkaa** [comment]
> I have encountered some issues while testing this PR, which is when changing chats, the user list does not update, please fix it

It was updating, but just adding list of users from new chat to an old one. Fixed it:
```
if isInitial {
    self.chatMembers = mappedUsers
} else {
    self.chatMembers += mappedUsers
}
```

**Comment by levochkaa** [comment]
> And also the user list update process introduces tremendous lag, probably related to fetching everything on the main thread

hope it is fixed, i have removed fetching from the main thread to background

**Comment by ggoraa** [comment]
Thanks for the fixes! I will test these changes later this day :)

**Comment by ggoraa** [comment]
Just did the testing:

1. A clear of the user list still does not work, that thing still thinks that it's in a previous chat
2. Performance problems did go away, good job!
3. Also, to fetch the next batch of users the user should do a large overscroll to make it fetch new users, which will definitely not work for folks with mouses, and is generally not that easy to use. I think it's better to fetch some time before reaching the end, so it doesn't feel as janky

**Comment by ggoraa** [comment]
UPD: tried again, somehow it works differently now, but still broken

Now after changing a chat, the user list does not update at all

**Comment by ggoraa** [comment]
Bruh I tried again and the behavior returned back to how it was lmao

**Comment by c-h3xcode** [comment]
@ggoraa А на линукс е эта проблема тоже прослеживается?

**Comment by ggoraa** [comment]
Tested the new update, now it works as expected! Kind of...
If I select a chat which is not a group, it will clear the entire list, as expected, but when I select a group again, it will not show a list of users from that chat, it will stay clear

**Comment by ggoraa** [comment]
And, if you can, it will be really good if you will add support for updates from TDLib, which will make that list live, and make it update itself when data changes

**Comment by ggoraa** [comment]
Fuck it, gonna YOLO it and do a merge

**Pull request merged**
